# -*- coding: utf-8 -*-
"""education_script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bwXXsFAnScL3FXDAayPcF5sbybgmHw_d
"""

import pandas as pd
import numpy as np

education_df = pd.read_csv("./education.csv")
health_df = pd.read_csv("./health.csv")

countries = ["Canada", "United States", "United Kingdom", "France", "Germany", "Sweden", "Australia", "Denmark", "Belgium"]

#canada_health = health_df[health_df['Country Name'] == 'Canada']
health_indicators = set(health_df["Series Name"])
health_indicators.discard('nan')
education_indicators =  set(education_df["Series"])
education_indicators.discard('nan')
indicators = health_indicators.union(education_indicators)
indicators.discard('nan')
indicators = list(indicators)
indicators

health_df[(health_df['Country Name'] == 'Canada') & (health_df["Series Name"] == 'School enrollment, primary (% gross)')]["2005"].item()

list(map(str, range(2005,2021)))

res = []
for year in list(map(str, range(2005,2021))):
  for country in countries:
    output = [country, year]
    for indicator in indicators:
      if indicator in education_indicators:
        output.append(education_df[(education_df['Country Name'] == country) & (education_df["Series"] == indicator)][year].item())
      elif indicator in health_indicators:
        output.append(health_df[(health_df['Country Name'] == country) & (health_df["Series Name"] == indicator)][year].item())
    res.append(output.copy())
res = np.array(res)

columns = ["Country Name", "Year"] + indicators
education_dimension = pd.DataFrame(res, columns=columns)

education_dimension.to_csv()